# -*- coding: utf-8 -*-
"""TesteMulticanal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgCiVYc4GzasbigSjSdFh8PUeh7I-4jY
"""

import numpy as np
from numpy import linalg as LA
from scipy.linalg import toeplitz
from scipy.linalg import null_space
import matplotlib.pyplot as plt

def matrix_to_vector(input):
    input_h, input_w = input.shape
    output_vector = np.zeros(input_h*input_w, dtype=input.dtype)
    # flip the input matrix up-down because last row should go first
    input = np.flipud(input)
    for i,row in enumerate(input):
        st = i*input_w
        nd = st + input_w
        output_vector[st:nd] = row

    return output_vector

def vector_to_matrix(input, output_shape):
    output_h, output_w = output_shape
    output = np.zeros(output_shape, dtype=input.dtype)
    for i in range(output_h):
        st = i*output_w
        nd = st + output_w
        output[i, :] = input[st:nd]
    # flip the output matrix up-down to get correct result
    output=np.flipud(output)
    return output

def convmtx2(I, F):
  I_row_num, I_col_num = I.shape
  F_row_num, F_col_num = F.shape
  O_row_num = I_row_num + F_row_num - 1
  O_col_num = I_col_num + F_col_num - 1

  F_zero_padded = np.pad(F, (( O_row_num - F_row_num , 0),(0, O_col_num - F_col_num )),'constant', constant_values =0)

  # use each row of the zero-padded F to creat a toeplitz matrix.
  #  Number of columns in this matrices are same as numbe of columns of input signal
  toeplitz_list = []
  for i in range(F_zero_padded.shape[0]-1, -1, -1): # iterate from last row to the first row
      c = F_zero_padded[i, :] # i th row of the F
      r = np.r_[c[0], np.zeros(I_col_num-1)] # first row for the toeplitz fuction should be defined otherwise
                                                          # the result is wrong
      toeplitz_m = toeplitz(c,r) # this function is in scipy.linalg library
      toeplitz_list.append(toeplitz_m)
      #print('F '+ str(i)+'\n', toeplitz_m)

  # doubly blocked toeplitz indices:
  #  this matrix defines which toeplitz matrix from toeplitz_list goes to which part of the doubly blocked
  c = range(1, F_zero_padded.shape[0]+1)
  r = np.r_[c[0], np.zeros(I_row_num-1, dtype=int)]
  doubly_indices = toeplitz(c, r)
  #print('doubly indices \n', doubly_indices)

  ## creat doubly blocked matrix with zero values
  toeplitz_shape = toeplitz_list[0].shape # shape of one toeplitz matrix
  h = toeplitz_shape[0]*doubly_indices.shape[0]
  w = toeplitz_shape[1]*doubly_indices.shape[1]
  doubly_blocked_shape = [h, w]
  doubly_blocked = np.zeros(doubly_blocked_shape)

  # tile toeplitz matrices for each row in the doubly blocked matrix
  b_h, b_w = toeplitz_shape # hight and withs of each block
  for i in range(doubly_indices.shape[0]):
      for j in range(doubly_indices.shape[1]):
          start_i = i * b_h
          start_j = j * b_w
          end_i = start_i + b_h
          end_j = start_j + b_w
          doubly_blocked[start_i: end_i, start_j:end_j] = toeplitz_list[doubly_indices[i,j]-1]

  #print('doubly_blocked: ', doubly_blocked)
  out_shape = [O_row_num, O_col_num]
  return doubly_blocked, out_shape

def deconv2(X,vF0,nIter):
  vF1  = np.copy(vF0)

  for i in range(nIter):

    G    = mX.T @ mX @ vF1
    L    = G - vF1.T @ G * vF1
    L    = L/LA.norm(L)
    tha  = -np.pi/180
    thb  = 0

    vF1b = np.cos(thb)*vF1 + np.sin(thb)*(L)
    Jb   = vF1b.T @ mX.T @ mX @ vF1b
    phi  = 2.-(1.+np.sqrt(5.))/2.

    for j in range(50):

      thc = tha+phi*(thb-tha)
      thd = thb+phi*(tha-thb)

      vF1c = np.cos(thc)*vF1 + np.sin(thc)*(L)
      vF1d = np.cos(thd)*vF1 + np.sin(thd)*(L)
      Jc   = vF1c.T @ mX.T @ mX @ vF1c
      Jd   = vF1d.T @ mX.T @ mX @ vF1d

      if Jc > Jd:
        tha = np.copy(thc)
      else:
        thb = np.copy(thd)
        Jb  = np.copy(Jd)

    vF1 = np.cos(thb)*vF1 + np.sin(thb)*(L)

    mE = np.matmul(mX, vF1)
    J  = np.matmul(mE,mE.T)
    if (i + 1) % 100 == 0:
        print([i, J])

  return vF1

#I = np.array([[0, 0, 0, 0],[0, 2, 0, 0],[0, 0, -2, 0],[0, 0, 0, 0]])

I = np.zeros((16, 16), dtype=int)

# Define the pixels for the letter 'A' (scaled for 16x16)
# Top bar
I[0:2, 4:12] = 1
# Sides
I[2:14, 2:4] = 1
I[2:14, 12:14] = 1
# Middle bar
I[7:9, 4:12] = 1

#F1 = np.array([[1.0, 0.5],[0.5, 0.5]])
#F2 = np.array([[1.0, -0.5],[-0.5, -0.5]])

F1 = np.array([[0.0, 0.0, 0.0],[0.0, 1, 0.5],[0.0, 0.5, 0.5]])
F2 = np.array([[-0.5, -0.5, 0.0],[-0.5, 1, 0.0],[0.0, 0.0, 0.0]])
#F2 = np.array([[0.0, 0.0, 0.0],[0.0, 1, -0.5],[0.0, -0.5, -0.5]])

I_row_num, I_col_num = I.shape
F1_row_num, F1_col_num = F1.shape
F2_row_num, F2_col_num = F2.shape

O_row_num = I_row_num + F1_row_num - 1
O_col_num = I_col_num + F1_col_num - 1

mI, out_shape = convmtx2(F1, I)

# call the function
vectorized_F1 = matrix_to_vector(F1)
vectorized_F2 = matrix_to_vector(F2)

# get result of the convolution by matrix mupltiplication
vectorized_X1 = np.matmul(mI, vectorized_F1)
vectorized_X2 = np.matmul(mI, vectorized_F2)

# reshape the raw result to desired matrix form

X1 = vector_to_matrix(vectorized_X1, out_shape)
X2 = vector_to_matrix(vectorized_X2, out_shape)

mX1, out_shape = convmtx2(F1, X1)
mX2, out_shape = convmtx2(F1, X2)

vectorized_mX1 = np.matmul(mX1, vectorized_F2)
vectorized_mX2 = np.matmul(mX2, vectorized_F1)

mX = np.concatenate((-mX2, +mX1), axis=1)
vF = np.concatenate((vectorized_F1, vectorized_F2), axis=0)

vFnn = null_space(mX)
vFn = vFnn/LA.norm(vFnn,np.inf)
vFn = vFn.T
print(vFn)

LA.norm(mX @ vFnn,axis=0)

vF0   = np.array([0., 0., 1., 0., 0., 0., 1., 0.])
vF0   = np.array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

nIter = 2000
vF1   = deconv2(mX,vF0,nIter)

F1_shape = [F1_row_num, F1_col_num]
F1est = vector_to_matrix(vF1[0:F1_row_num*F1_col_num], F1_shape)
F2est = vector_to_matrix(vF1[F1_row_num*F1_col_num:2*F1_row_num*F1_col_num], F1_shape)

F1est = F1est/np.max(np.abs(F1est))
F2est = F2est/np.max(np.abs(F2est))

print(F1)
print(F1est)

print(F2)
print(F2est)

np.max(np.abs(F1est))

all_data = np.concatenate((I.flatten(), F1.flatten(), F2.flatten()))
global_vmin = all_data.min()
global_vmax = all_data.max()

print(f"Global Min: {global_vmin}")
print(f"Global Max: {global_vmax}")

plt.figure(figsize=(15, 5))

plt.subplot(3, 3, 1)
plt.imshow(I, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Reference Image I')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 2)
plt.imshow(F1, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Kernel F1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 3)
plt.imshow(F2, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Kernel F2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 5)
plt.imshow(X1, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Image I*F1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 6)
plt.imshow(X2, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Image I*F2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 8)
plt.imshow(F1est, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 3, 9)
plt.imshow(F2est, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 5))

plt.subplot(3, 2, 1)
plt.imshow(F1, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Kernel F1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 2, 2)
plt.imshow(F2, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Kernel F2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 2, 3)
plt.imshow(F1est, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 2, 4)
plt.imshow(F2est, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 2, 5)
plt.imshow(F1est-F1, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 1 - Kernel 1')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.subplot(3, 2, 6)
plt.imshow(F2est-F2, cmap='viridis', vmin=global_vmin, vmax=global_vmax)
plt.colorbar(label='Value')
plt.title('Estimated Kernel 2 - Kernel 2')
plt.xlabel('Column Index')
plt.ylabel('Row Index')

plt.tight_layout()
plt.show()